# Generated by Django 5.1.7 on 2025-03-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='reminder_days',
            field=models.IntegerField(choices=[(1, '1 Day Before'), (3, '3 Days Before'), (7, '7 Days Before')], default=7),
        ),
    ]
