# Generated by Django 5.1.7 on 2025-03-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_subscription_reminder_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='reminder_date',
        ),
    ]
