# Generated by Django 5.1.7 on 2025-03-26 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_subscription_reminder_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='predefined_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.predefinedsubscription'),
        ),
    ]
